### ISSUE TITLE
Expose raw response JSON

### ISSUE THREAD

**Issue by lthurston** [jordikroon/Php-Google-Vision-Api#15]
I'd like to have access to the raw JSON within my application for displaying to technically inclined users. Displaying print_r($annotateImageResponse, true) is too cluttered with irrelevant class names for that purpose.

I'm happy to implement a switch of some kind for returning JSON rather than an AnnotateImageResponse. If you have a preferred way of doing it, I'll defer to your approach.

I guess if I were to stab wildly at it, I would extract the response parsing from VisionRequest::send(), create VisionRequest::getResponse(), which would contain the AnnotateImageResponse content or exception, and a VisionRequest::getJsonResponse() which would return the raw JSON.

I'd then modify Vision/Vision::request() to switch based on a return type (passed as an optional argument).

What do you think?

**Comment by jordikroon** [comment]
Agreed. Being able to return the raw response would help with debugging. It would also give users the ability to use (experimental) features that this library hasn't implemented yet.

Your approach sounds good to me. Would you mind creating a PR for it, with tests included? Thanks for your suggestion!

**Comment by lthurston** [comment]
Can do. I'll try to get started on it today.

**Comment by lthurston** [comment]
https://github.com/lthurston/Php-Google-Vision-Api/commit/868676dbb9ba1196ac5a38e8b092dce280eb8aaf

A work in progress. Totally untested. I'll circle back, but probably not until next week.

**Comment by jordikroon** [comment]
Merged. Thanks!
