### ISSUE TITLE
Undefined index: property in BlocksStrategy.php (line 58)

### ISSUE THREAD

**Issue by yurik94** [jordikroon/Php-Google-Vision-Api#17]
```
$vision = new \Vision\Vision(
		    config( 'vision.api_key' ),
		    [
			    // See a list of all features in the table below
			    // Feature, Limit
			    new \Vision\Feature( \Vision\Feature::DOCUMENT_TEXT_DETECTION, 100 ),
		    ]
	    );
	    $response = $vision->request(
		    new \Vision\Image( storage_path( 'app/daf/0/') . 'test.jpg' )
	    );
```

![test](https://user-images.githubusercontent.com/13189646/32833516-6ace73fa-c9ff-11e7-93ba-0ff09fd14b6e.jpg)

(1/1) ErrorExceptionUndefined index: property
--
in BlocksStrategy.php (line 58)
at HandleExceptions->handleError(8, 'Undefined index: property', 'C:\\Users\\yuri_\\PhpstormProjects\\daf_backend\\vendor\\jordikroon\\google-vision\\src\\Hydrator\\Strategy\\BlocksStrategy.php', 58.....

**Comment by jordikroon** [comment]
Thanks for reporting this issue. Looks like an optional value Google only sends if the value is not empty. Thus the mapping attempts to access the undefined index.

I'll push a fix this evening that fixes this error.

**Comment by yurik94** [comment]
Thanks!

Il 16 nov 2017 13:58, "Jordi Kroon" <notifications@github.com> ha scritto:
