### ISSUE TITLE
Crophints: Give aspect ratio as parameter

### ISSUE THREAD

**Issue by SativaNL** [jordikroon/Php-Google-Vision-Api#19]
If you look at the documentation you can see that you can give an aspect ratio as parameter. But I don't know how to do this with your script.

https://stackoverflow.com/questions/44304400/can-i-give-aspect-ratio-in-google-vision-api
https://cloud.google.com/vision/docs/crop-hints

How can I set a parameter with the request?

**Comment by jordikroon** [comment]
Hi there,

I've never been aware of these extra parameters. As of now the only option is to override getPayload by extending the VisionRequest. 

I'll dig into this later today and update the library to match the extra options.
https://cloud.google.com/vision/docs/reference/rest/v1/images/annotate#ImageContext

**Comment by jordikroon** [comment]
@SativaNL Haven't forgotten this. I've implemented the extra parameters. See below for a small how-to. 

It follows the Google Vision documentation https://cloud.google.com/vision/docs/reference/rest/v1/images/annotate#ImageContext

```php
$imageContext = new \Vision\Annotation\ImageContext();
$imageContext->setLanguageHints(['test']);
$imageContext->setLatLongRect(new \Vision\Annotation\LatLongRect(
    new \Vision\Annotation\LatLng(1.00, 2.00),
    new \Vision\Annotation\LatLng(3.00, 4.00)
));

$imageContext->setCropHintsParams(new \Vision\Annotation\CropHintsParams([1.27]));

$vision = new \Vision\Vision(
    'api-key',
    [
        // See a list of all features in the table below
        // Feature, Limit
        new \Vision\Feature(\Vision\Feature::CROP_HINTS, 100),
    ],
    $imageContext
);

```
