### ISSUE TITLE
ErrorException in ParagraphsStrategy.php line 57: Undefined index: property

### ISSUE THREAD

**Issue by bhuvan-0078** [jordikroon/Php-Google-Vision-Api#31]
This error is thow when DOCUMENT_TEXT_DETECTION is applied, have any luck ?

$apiKey = "API_KEY";
		$vision = new \Vision\Vision(
			$apiKey, 
			[
				// See a list of all features in the table below
				// Feature, Limit
				new \Vision\Feature(\Vision\Feature::DOCUMENT_TEXT_DETECTION, 1),
			]
		);

		$imagePath = public_path().'/uploads/1.jpg';
		$response = $vision->request(
			// See a list of all image loaders in the table below
			new \Vision\Request\Image\LocalImage($imagePath)
		);

**Comment by jordikroon** [comment]
Hi there,

Sorry that this has taken me this long. This has just been added to the 1.8.0 release.
Thanks for reporting.
