### ISSUE TITLE
Vision Request error

### ISSUE THREAD

**Issue by davodm** [jordikroon/Php-Google-Vision-Api#34]
Hi, I use your library in Codeigniter,
But it gives me Parse error:

Parse error: syntax error, unexpected '.', expecting ',' or ';' in /srv/beporsim/application/third_party/gvision/jordikroon/google-vision/src/Request/VisionRequest.php on line 17
A PHP Error was encountered

Severity: Parsing Error

Message: syntax error, unexpected '.', expecting ',' or ';'

Filename: Request/VisionRequest.php

Line Number: 17

[givision.txt](https://github.com/jordikroon/Php-Google-Vision-Api/files/2442999/givision.txt)

My library has been attached.

Kindest Regards,
Davod

**Comment by jordikroon** [comment]
Hello, thanks for reporting.

Could you post your PHP version here? I'll take a look into this.

**Comment by jordikroon** [comment]
Hi @davodm! Haven't heard from you back. Are you still experiencing issues? 
If so, could you write your PHP version here. 

Thanks!

**Comment by jordikroon** [comment]
Hi, I'm closing this issue as I haven't heard back from you. Assuming the issue has been resolved.
