### ISSUE TITLE
Hydrator/Strategy/WordsStrategy - Undefined index: property

### ISSUE THREAD

**Issue by JuanAlessandrini** [jordikroon/Php-Google-Vision-Api#36]
when i was using a Feature::TEXT_DETECTION brings me an error on:
line 58 of jordikroon/google-vision/src/Hydrator/Strategy/WordsStrategy.php

**Comment by jordikroon** [comment]
Thanks for reporting @JuanAlessandrini! Google has this odd inconsistent habit of removing properties when they are null thus resulting in undefined indexes. 

I've made the values optional and packed it in a 1.8.2.

**Comment by JuanAlessandrini** [comment]
Sorry, but is'nt still working. i dont know why, because i cant get the server error, but brings me a 500 as response.

**Comment by jordikroon** [comment]
Seems composer didn't automatically persist the versioning. Should be fixed. Could you try doing a `composer update` and try again?

**Comment by JuanAlessandrini** [comment]
no, just update the "src" folder on mi server and run the code!
